language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - TZ="US/Central"
  - TZ="UTC"
install:
  - pip install six
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - python updatezinfo.py
script:
  - python setup.py test
sudo: false
