language: python
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4"
  - "pypy3"

matrix:
  allow_failures:
    - python: "nightly"

before_install:
  # Install codecov
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install coverage==3.7.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION < '3.0' ]]; then pip install mock; fi
  - pip install codecov
  - pip install freezegun
  - pip install pytest

install:
  - pip install six
  - ./ci_tools/retry.sh python updatezinfo.py

script:
  - coverage run --omit=setup.py,dateutil/test/* -m pytest -v

after_success:
  - codecov

sudo: false
