build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python33"
    - PYTHON: "C:/Python33-x64"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python34-x64"
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python36-x64"
install:
  # Add PostgreSQL (zic), Python and scripts directory to current path
  - set path=c:\Program Files\PostgreSQL\9.3\bin\;%PATH%
  - set path=%PATH%;%PYTHON%;%PYTHON%/Scripts

  # If this isn't done, I guess Appveyor will install to the Python2.7 version
  - set pip_cmd=%PYTHON%/python.exe -m pip

  # Download scripts and dependencies
  - ps: Start-FileDownload 'https://bootstrap.pypa.io/get-pip.py'
  - "%PYTHON%/python.exe get-pip.py"
  - "%pip_cmd% install six"
  - "%pip_cmd% install coverage"
  - "%pip_cmd% install codecov"

  # This frequently fails with network errors, so we'll retry it up to 5 times
  # with a 1 minute rate limit.
  - "ci_tools/retry.bat %PYTHON%/python.exe updatezinfo.py"
  # This environment variable tells the test suite it's OK to mess with the time zone.
  - set DATEUTIL_MAY_CHANGE_TZ=1
test_script:
  - "coverage run --omit=setup.py,dateutil/test/* setup.py test"
after_test:
  - "codecov"
